beginningdjango-master/4_django_jinja_templates/coffeehouse/about/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^(?P<store_id>\d+)/$',views.index,name="index_withid"),
    url(r'^contact/$',views.contact,name="contact"),
    url(r'^contact/(?P<store_id>\d+)/$',views.contact,name="contact_withid"),
]

beginningdjango-master/4_django_jinja_templates/coffeehouse/drinks/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import include, url
from coffeehouse.drinks import views as drinks_views

urlpatterns = [
    url(r'^$',drinks_views.index,name="index"),
    url(r'^(?P<drink_type>\D+)/$',drinks_views.detail,name="detail"),
]

beginningdjango-master/4_django_jinja_templates/coffeehouse/stores/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import include, url

from . import views 

urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^(?P<store_id>\d+)/$',views.detail,name="detail"),
    url(r'^(?P<store_id>\d+)/about/',include('coffeehouse.about.urls',namespace="stores_about")),
]

beginningdjango-master/4_django_jinja_templates/coffeehouse/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.contrib import admin


from coffeehouse.drinks.urls import urlpatterns as drinks_url_patterns

urlpatterns = [
    url(r'^$',TemplateView.as_view(template_name='homepage.html'),name="homepage"),
    url(r'^about/', include('coffeehouse.about.urls',namespace="about")),
    url(r'^drinks/', include(drinks_url_patterns,namespace="drinks")),
    url(r'^stores/',include('coffeehouse.stores.urls',namespace="stores")),
    url(r'^online/',TemplateView.as_view(template_name='online/index.html'),name='online'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
]

beginningdjango-master/4_django_jinja_templates/coffeehouse/about/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

beginningdjango-master/4_django_jinja_templates/coffeehouse/drinks/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

beginningdjango-master/4_django_jinja_templates/coffeehouse/stores/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

beginningdjango-master/4_django_jinja_templates/coffeehouse/about/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from coffeehouse.stores.views import STORE_LIST
from django.http import Http404

def index(request,store_id=None):
    # Create fixed data structures to pass to template
    # data could equally come from database queries
    if store_id == None:
        store = STORE_LIST[0]
    elif store_id == "1":
        store = STORE_LIST[1]
    elif store_id == "2":
        store = STORE_LIST[2]
    elif store_id == "3":
        store = STORE_LIST[3]
    else:
        raise Http404
    return render(request,'about/index.html',{'store':store})

def contact(request,store_id=None):
    # Create fixed data structures to pass to template
    # data could equally come from database queries
    if store_id == None:
        store = STORE_LIST[0]
    elif store_id == "1":
        store = STORE_LIST[1]
    elif store_id == "2":
        store = STORE_LIST[2]
    elif store_id == "3":
        store = STORE_LIST[3]
    else:
        raise Http404
    return render(request,'about/contact.html',{'store':store})

beginningdjango-master/4_django_jinja_templates/coffeehouse/drinks/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# Create your views here.
from django.shortcuts import render

def index(request):
    drink_list = ['mocha','espresso','latte']
    return render(request,'drinks/index.html',{'drinks':drink_list})

def detail(request,drink_type):
    if drink_type == "mocha":
        description = "Our superior dark coffee made from beans from Arabia"
    elif drink_type == "espresso":
        description = "Our strong coffee brewed by forcing steam under pressure through darkly roasted, powdered coffee beans"
    else: 
        description = "Our coffee made with hot milk"
    return render(request,'drinks/detail.html',{'drink':drink_type,'drink_description':description})

beginningdjango-master/4_django_jinja_templates/coffeehouse/stores/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# Create your views here.
from django.shortcuts import render
from django.core.exceptions import PermissionDenied,SuspiciousOperation
from django.http import Http404,HttpResponsePermanentRedirect

STORE_LIST =  [{'id':0,'name':'Corporate','address':'624 Broadway','city':'San Diego','state':'CA','email':'corporate@coffeehouse.com'},{'id':1,'name':'Downtown','address':'Horton Plaza','city':'San Diego','state':'CA','email':'downtown@coffeehouse.com'},{'id':2,'name':'Uptown','address':'1240 University Ave','city':'San Diego','state':'CA','email':'uptown@coffeehouse.com'},{'id':3,'name':'Midtown','address':'784 W Washington St','city':'San Diego','state':'CA','email':'midtown@coffeehouse.com'}]

def index(request,location=None):
    store_list = STORE_LIST[1:]
    return render(request,'stores/index.html',  {'stores':store_list})    

def detail(request,store_id=1,location=None):
    # Access store_id parameter with 'store_id' variable 
    # Access location parameter with 'location' variable
    # Extract 'hours', 'lat' or 'lon' values appended to url as
    # e.g. ?hours=sunday&latitude=32.71&longitude=-117.16
    # 'hours' has value 'sunday' or '' if hours not in url
    # 'latitude' has value 32.71 or 0 if latitude not in url
    # 'longitude' has value -117.16 or 0 if longitude not in url
    hours = request.GET.get('hours', '')
    latitude = request.GET.get('latitude', 0)
    longitude = request.GET.get('longitude', 0)    
    # Validation for hours variables
    if hours not in ['','sunday','monday','tuesday','wednesday','thursday','friday','saturday']:
        raise Http404
    # Validation for latitude & longitude 
    try:
        # latitude and longitude should be cast'able to float if numbers
        float(latitude)
        float(longitude)
    except ValueError:
        raise SuspiciousOperation
    # Validation if latitude in range
    if float(latitude) > 90 or float(latitude) < -90:
        raise Exception("Invalid latitude, min -90 and max 90")
    # Validation if longitude in range
    if float(longitude) > 180 or float(longitude) < -180:
        raise Exception("Invalid longitude, min -180 and max 180")
    # If latitude==90 and longitude==90, redirect to maps.google.com
    if float(latitude) == 90 or float(longitude) == 90:
        return HttpResponsePermanentRedirect("http://maps.google.com/")
    # Create fixed data structures to pass to template
    # data could equally come from database queries
    if store_id == "1":
        store = STORE_LIST[1]
    elif store_id == "2":
        store = STORE_LIST[2]
    elif store_id == "3":
        store = STORE_LIST[3]
    else:
        raise Http404
    store_amenities = ['WiFi','A/C']
    store_menu = ((0,''),(1,'Drinks'),(2,'Food'))
    vals_for_template = {'store':store,'store_amenities':store_amenities,'store_menu':store_menu}
    return render(request,'stores/detail.html', vals_for_template)

beginningdjango-master/4_django_jinja_templates/coffeehouse/templates/base.html
{% macro coffeestore(name, id='', address='', city='San Diego', state='CA', email=None) -%}
    <a id="{{id}}"></a>
    <h4>{{name}}</h4>
    <p>{{address}} {{city}},{{state}}</p>
    {% if email %}<p><a href='mailto:{{email}}'>{{email}}</a></p>{% endif %}
{%- endmacro %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title%}{% endblock%}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block metadescription%}{% endblock %}">
    <meta name="keywords" content="{% block metakeywords%}{% endblock %}">
    <meta name="author" content="">

    <!-- styles -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-header">
          <a class="navbar-brand" href="/">Coffeehouse</a>
	  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	    <span class="icon-bar"></span>
	    <span class="icon-bar"></span>
	    <span class="icon-bar"></span>
	  </button>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'homepage' %}">Home</a></li>
          <li><a href="{% url 'about:index' %}">About</a></li>
          <li><a href="{% url 'about:contact' %}">Contact</a></li>
	  <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Site sections<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'stores:index' %}">Stores</a></li>
	      <li><a href="{% url 'drinks:index' %}">Drinks</a></li>
	      <li><a href="{% url 'online' %}">Order online</a></li>
            </ul>
	  </li>	  
        </ul>
      </div><!--/.navbar-collapse -->
    </div>

    <div class="container">

   {% block nobreadcrumb %}
    <ul class="breadcrumb">
      {% block breadcrumb %}     
      {% endblock %}
    </ul> 
   {% endblock %}
 
      {% block content %}
      {% endblock %}
      <hr>

      <footer>
        <p>{% include "footer.html" %}</p>
      </footer>
    </div> <!-- /container -->

    <!-- Javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script   src="http://code.jquery.com/jquery-1.12.2.min.js"   integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="   crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  </body>
</html>

beginningdjango-master/4_django_jinja_templates/coffeehouse/templates/footer.html
&copy; Coffeehouse 2018

beginningdjango-master/4_django_jinja_templates/coffeehouse/templates/homepage.html
{% extends "base.html" %} 

{% block title %} Coffeehouse home page {% endblock %} 
{% block nobreadcrumb %}{% endblock %}
{% block content %}

  <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1>Welcome to the Coffeehouse!</h1>
        <p><a class="btn btn-primary btn-lg" href="{% url 'about:index'%}">Learn more &raquo;</a></p>
	{% set myvar="Open since 1965!" %} 	
	{{myvar|customcoffee("lead muted")}}
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Stores</h2>
          <p><a class="btn btn-default" href="{% url 'stores:index' %}">View store details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Drinks</h2>
          <p><a class="btn btn-default" href="{% url 'drinks:index' %}">View drink details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Order online</h2>
          <p><a class="btn btn-default" href="{% url 'online' %}">Order online &raquo;</a></p>
        </div>
      </div>
{% endblock %}